### ISSUE TITLE
Doesn't pickup content of "display:none"-elements on webkit

### ISSUE THREAD

**Issue by tliebig** [NeXTs/Jets.js#10]
Hi,

I'm using `display:none` to add some text that should be searchable throught jetJS, but not visible. 

On Firefox, this works just fine, but on Chrome/Safari the content of the elements never gets added to the `data-jets=""` attribute.

Changing the element to `position:absolute`and moving it off the viewport works. I guess something in the jetJS engine keeps the content from being picked up when the element is hidden.

Is there any way to make jetJS pick up the content of hidden elements as well?

**Comment by NeXTs** [comment]
Hi!
Could you please provide codepen/jsfiddle example?

**Comment by tliebig** [comment]
Sure. This works on firefox, but not on Chrome/Webkit:
http://jsfiddle.net/t44hs75t/

**Comment by NeXTs** [comment]
It turns out that [.innerText which we used](https://github.com/NeXTs/Jets.js/blob/20d5b5a0bab0abc01140f7e0c5831428f3e5af84/jets.js#L92) as preferred method to fetch text content [did not return the text of hidden elements](http://perrymitchell.net/article/element-innertext-textcontent-for-all-browsers/), while fallback .textContent did.

[This article](http://www.kellegous.com/j/2013/02/27/innertext-vs-textcontent/) and [order of these methods in jQuery sources](https://github.com/jquery/jquery/blob/d92310050ca7bf0b33825d64e052f9a8809c3e9e/test/data/jquery-1.9.1.js#L5007) forced me to swap them.

**Comment by tliebig** [comment]
Works like the proverbial charme. Thanks alot for the quick fix!
