### ISSUE TITLE
Reversing the logic to show, not hide

### ISSUE THREAD

**Issue by mattgreenfield** [NeXTs/Jets.js#11]
Is it possible to reverse the search logic so that I can set all items to `display: none` in my CSS and then have jets.js add `display: block` to the search results.

An alternative would be to hide all my items with `display:none` and remove that as soon as any character is input in the search field. There maybe need to be a delay to stop all the results showing when only one character is input (thinking about it, a parameter to set how many characters are input before the search runs may be handy...).

But it would be nice if this was built in.

**Comment by NeXTs** [comment]
Hi Matt
If you want to use list.js why do you need jets.js then?

**Comment by mattgreenfield** [comment]
Sorry @NeXTs thats a typo, too many tabs open!
Thanks for the plugin by the way, works great! 
Is this something I could make a pull request for?

**Comment by NeXTs** [comment]
Inversed logic (to hide) was made because it's more universal solution than displaying necessary rows.
You never knew which display type should be set: block or inline-block or inline or table-row, etc...

Of course you able to add property and specify it's type by hands during initialisation, but it is not good solution as for me.
