### ISSUE TITLE
'Element' is undefined in IE9

### ISSUE THREAD

**Issue by jackroscoe** [NeXTs/Jets.js#15]
Firstly thanks for all your work on this!

I'm not sure if this is to do with my implementation but a large portion of my IE9 visitors are seeing this error in response to the use of `Element.prototype`.

The only details I have from the error are `window.onerror 'Element' is undefined` and a line number which points me to the minified Jets file.

I only know about the error due to my Bugsnag reports but can't actually replicate it myself via BrowserStack.

So I'm wondering, has anyone else come across this?

**Comment by NeXTs** [comment]
Hi Jack

Element.prototype actually used in [plugin's sources](https://github.com/NeXTs/Jets.js/blob/master/jets.js#L157). It belongs to :scope polyfill taken from [SO](http://stackoverflow.com/a/17989803/1221082).

I can not reproduce it on my IE 9 (in emulation mode) so I recommend to duplicate your question to that [SO answer](http://stackoverflow.com/a/17989803/1221082) to warn others that that solution has some problems at IE9.

I'll google what may be wrong with Element at ie9 meanwhile.

**Comment by NeXTs** [comment]
Are you sure that it does not work exactly at IE9 and not at IE8?

Because there [are](http://stackoverflow.com/questions/4193769/augmenting-the-prototype-of-dom-element-nodes) [some](http://stackoverflow.com/questions/10809323/can-i-override-prototype-functions-in-ie8) [problems](http://stackoverflow.com/questions/592815/is-there-really-no-way-to-expose-the-prototype-of-a-html-element-in-ie-8) with augmenting the prototype of Element exactly at IE8.

Can you share the link to website where problem occurs with me?

**Comment by jackroscoe** [comment]
Hey Denis,

Thanks for the fast reply.

I'm not totally sure. I can't replicate it in IE9 either, it's just coming through in my reports from [Bugsnag](https://bugsnag.com/). I wonder if it could be an issue with the error reporting service if you can't see it either.

The website is http://novni.com. The component that's using Jets is actually hidden from view at the moment, which makes it even more unusual.

I'll try to investigate more before going to SO.

**Comment by NeXTs** [comment]
@jackroscoe was you able to reproduce this issue?

**Comment by NeXTs** [comment]
Closing due inactivity
